version: 2

models:
  - name: svc_investment_signals.int_signal_price_windows
    description: Привязка сигнала к цене в момент сигнала и будущим ценовым окнам.
    config:
      schedule: "@hourly"
    columns:
      - name: signal_id
        tests:
          - unique
          - not_null
      - name: price_at_signal
        tests:
          - not_null
